Add Moderations API
valentinegb/openai pull request #50
Opened 2023-03-25 16:24 UTC by rukolahasser

Implementation of `moderations` api

2023-03-26 20:32 UTC, valentinegb requested changes
Make structure fields public, currently inaccessible outside of `moderations` module.

2023-03-26 20:37 UTC, valentinegb requested changes

2023-03-26 20:37 UTC, valentinegb commented on src/moderations.rs
> +    #[serde(rename = "results")]
Remove unnecessary field rename.

```suggestion
```

2023-03-27 02:52 UTC, rukolahasser commented on src/moderations.rs
> +    #[serde(rename = "results")]
Fixed

2023-03-27 02:53 UTC, rukolahasser commented
Changed all visibility modifiers to `pub`

2023-03-27 15:02 UTC, valentinegb requested changes

2023-03-27 15:02 UTC, valentinegb commented
Probably the last change requests haha, sorry-

2023-03-27 15:54 UTC, rukolahasser commented on src/moderations.rs
> +    pub flagged: bool,
Could you tell me where to check the schema? So my order is based on the example response:
```
{
  "id": "modr-5MWoLO",
  "model": "text-moderation-001",
  "results": [
    {
      "categories": {
        "hate": false,
        "hate/threatening": true,
        "self-harm": false,
        "sexual": false,
        "sexual/minors": false,
        "violence": true,
        "violence/graphic": false
      },
      "category_scores": {
        "hate": 0.22714105248451233,
        "hate/threatening": 0.4132447838783264,
        "self-harm": 0.005232391878962517,
        "sexual": 0.01407341007143259,
        "sexual/minors": 0.0038522258400917053,
        "violence": 0.9223177433013916,
        "violence/graphic": 0.036865197122097015
      },
      "flagged": true
    }
  ]
}

```

2023-03-27 16:09 UTC, rukolahasser commented on src/moderations.rs
> +}
fixed.

2023-03-27 16:09 UTC, rukolahasser commented on src/moderations.rs
> +#[derive(Deserialize, Clone, Debug)]
fixed.

2023-03-27 16:37 UTC, valentinegb commented on src/moderations.rs
> +    pub flagged: bool,
The schema is in this repository owned by OpenAI: https://github.com/openai/openai-openapi/blob/master/openapi.yaml

2023-03-28 04:03 UTC, rukolahasser commented on src/moderations.rs
> +    pub flagged: bool,
Gotcha, fixed!

2023-03-28 04:04 UTC, closed without merging

2023-03-28 04:15 UTC, rukolahasser commented
It was closed by accident, I've created a new one: https://github.com/valentinegb/openai/pull/54